jira_address = "" # insert your Jira address; example: https://jira.example.com
confluence_address = "" # insert your Confluence address; example: https://jira.example.com
access_token_pass = "DOMAIN_USER_PASSWORD"
access_token_login = "DOMAIN_USERNAME"
secret_tokens = ["api_key", "access_token", "password", "docs.google.com", "drive.google.com", "access_key", "secret_key"] # configure as one like
abuseipdb_token = "" # insert your AbuseIPDB API key here; 1000 requests per day, 30000 requests per month
ip2location_token = "" # insert your IP2location API key here; 30000 requests per month
wazuh_manager = "" # insert yuor Wazuh manager address here; example: https://10.10.10.34:55000
vmware_user = "" # VMWare user with read permissions
vmware_password = "" # vmware_user password
vmware_server = "" # example: example.com
vmware_tenant = "" # example: tenant
vmware_vdc_names = ["", "", ""] # VMWare vdc names; example: ["test", "prodlike", "prod"]
gitlab_private_token = "" # Gitlab token with read permissions
gitlab_base_url = "" # example: https:example.com
